networks:
  homepage-network:
    driver: bridge
services:
  homepage-frontend:
    build:
      context: ./frontend
    container_name: my-frontend-homepage
    networks:
      - homepage-network
    ports:
      - "80:80"
    depends_on:
      - homepage-backend
    volumes:
      - ./webserver-logs:/var/log/nginx
  homepage-backend:
    build:
      context: ./api
    container_name: my-api-homepage
    networks:
      - homepage-network
    ports:
      - "5202:5202"
    volumes:
      - ./cs-api-server-logs:/app/logs
