name: Gitleaks Scan

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']
  # Ermöglicht den manuellen Start über das GitHub-Actions-Tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # um nach Leaks in alten Commits zu suchen
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
